spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estoque_db
    username: postgres
    password: marimo1305

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true